version: '3.6'
services:
  nursequery:
    labels:
      - traefik.frontend.rule=Host:query.hellupline.com
    build:
      dockerfile: Dockerfile
      context: ./nursequery/
    image: hellupline/nursequery
    restart: always
    expose:
      - '8080'
    volumes:
      - booru_data:/root/.booru/
    depends_on:
      - traefik

  traefik:
    labels:
      - traefik.frontend.rule=Host:traefik.hellupline.com
      - traefik.port=8080
    image: traefik
    command: --api --docker
    restart: always
    expose:
      - '8080'
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  booru_data:
